### ISSUE TITLE
Unhandled Exception: Exception: Error fetching styles: Exception: Connection failed

### ISSUE THREAD

**Issue by andreabuttarelli** [buildwiththeta/buildwiththeta#89]
# **Title:** 

Unhandled Exception: Exception: Error fetching styles: Exception: Connection failed

## **Description:** 

This issue happens on macOS, working as expected in web

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Exception: Error fetching styles: Exception: Connection failed
#0      ThetaClient.initialize.<anonymous closure>.<anonymous closure> (package:theta/src/client.dart:18:18)
#1      Left.fold (package:either_dart/src/either.dart:169:15)
#2      ThetaClient.initialize.<anonymous closure> (package:theta/src/client.dart:17:13)
<asynchronous suspension>
#3      ThetaClient.initialize (package:theta/src/client.dart:16:38)
<asynchronous suspension>
#4      Theta._initializeCore (package:theta/src/instance.dart:110:5)
<asynchronous suspension>
#5      Theta._init (package:theta/src/instance.dart:116:5)
<asynchronous suspension>
#6      Theta.initialize (package:theta/src/instance.dart:88:5)
<asynchronous suspension>
#7      main (package:example/main.dart:7:3)
<asynchronous suspension>

---

## **Flutter Environment:** 

Provide information about your Flutter environment by running the command `flutter doctor -v` and pasting the output here.

## **App Version:** 

Which version of the app does this issue affect? If not applicable, write "N/A" or "Not applicable".

## **Device Information:** 

Please provide information about the device on which you're experiencing this issue (e.g., manufacturer, model, OS version).

---

## **Steps to Reproduce:** 

Provide a set of steps to reproduce the bug. Be as detailed as possible.

1. 
2. 
3. 
4. 

## **Expected Behavior:** 

What were you expecting to happen when you performed the steps above?

## **Actual Behavior:** 

What happened instead of the expected behavior? 

## **Logs:** 

Run `flutter run` or `flutter build` and paste any error logs that might help understand the issue. If the error log is too long, consider using a service like Gist to provide the link to the log.

## **Screenshots:**

If applicable, add screenshots to help explain your problem. Screenshots can be extremely helpful for understanding the issue, especially in the context of visual bugs.

## **Additional Context:** 

Add any other context about the problem here. This could include any relevant configuration, add-ons or libraries used, or other details that might help the developers understand the issue.

## **Possible Solution:** 

If you have an idea of a potential solution, describe it here. If not, feel free to skip this part.

---

Remember, providing as much detail as possible will make it easier for others to help you resolve the bug. If the bug is not immediately reproducible, it may be necessary to provide more context or a sample code snippet that demonstrates the issue.

**Comment by andreabuttarelli** [comment]
Solution: https://stackoverflow.com/questions/65458903/socketexception-connection-failed-os-error-operation-not-permitted-errno-1
